# Generated by Django 4.2.4 on 2023-08-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
